import type { Playbook } from "@/types/content";

export const playbooks: Playbook[] = [
  {
    slug: "ai-socratic-tutor",
    title: "AI Socratic Tutor",
    intro: "Learn by answering, not by collecting a finished explanation.",
    category: "Learning",
    outcome: "A study conversation that exposes gaps and checks whether you can transfer the idea.",
    bestFor: "A concept you need to understand, with time to practice.",
    need: ["A topic and your current level", "What you think you already know"],
    steps: [
      "State the topic, your level, and your current understanding.",
      "Ask for one question, not an explanation.",
      "Answer before you request a hint.",
      "Take the correction, then answer a retrieval question.",
      "Finish with a new problem that tests transfer.",
    ],
    produce: "Questions, hints, a correction, and a transfer problem.",
    failure: "A tutor that gives the answer before you attempt one.",
    verify: "Check corrections against trusted learning material.",
    example: "Use it on one concept from a course, chapter, or project you are in now.",
    prompt:
      "Act as a Socratic tutor for [topic] at [level]. Ask one question at a time and wait for my answer. Prefer hints before full explanations. Correct misunderstandings clearly, then ask me to explain the idea back. Finish with a new problem that tests transfer.",
  },
  {
    slug: "learn-by-teaching",
    title: "Learn by Teaching",
    intro: "Explain from memory, then study only the gaps.",
    category: "Learning",
    outcome: "A short list of weak spots and a cleaner explanation you can use again.",
    bestFor: "A topic you have already met and want to find out what actually stuck.",
    need: ["A topic you can try to explain without notes", "Permission to be corrected"],
    steps: [
      "Explain the topic from memory, without notes.",
      "Ask which links are unclear, missing, or wrong.",
      "Study only those gaps.",
      "Re-explain the topic in simpler words.",
      "Test the new explanation on a fresh example.",
    ],
    produce: "A gap list, a revised explanation, and one transfer check.",
    failure: "Polishing a summary you copied instead of exposing what you cannot say.",
    verify: "The revised explanation should survive a new example without the notes in front of you.",
    example: "Teach a concept you studied yesterday and stop at the first place you go vague.",
    prompt:
      "I will explain [topic] from memory. Do not teach yet. Mark what is unclear, missing, or incorrect, and why. After I study those gaps, ask me to re-explain simply and then give me a new example to solve.",
  },
  {
    slug: "deep-research-workflow",
    title: "Deep Research with a Stopping Rule",
    intro: "Research with a question, a source standard, and a reason to stop.",
    category: "Research",
    outcome: "A traceable synthesis that keeps evidence, inference, and unknowns apart.",
    bestFor: "A question where source quality changes the decision.",
    need: ["The question and the decision it serves", "Scope, dates, geography, and exclusions"],
    steps: [
      "Define the question and the purpose.",
      "Set scope, source hierarchy, and exclusions.",
      "Search broadly, then inspect primary sources.",
      "Separate evidence, inference, and unknowns.",
      "Synthesize, then stop when more research is unlikely to change the decision materially.",
    ],
    produce: "A claim-led brief with an evidence trail and a stopping note.",
    failure: "Collecting summaries without opening the sources they depend on.",
    verify: "Check important claims, dates, and quotations against the original sources.",
    example: "Start with the decision the research has to inform, not with a pile of links.",
    prompt:
      "Help me research [question] for [purpose]. First define scope, dates, geography, exclusions, and a source hierarchy. For each important claim, separate evidence, inference, and unknowns. End with open questions and a stopping rule: when more research is unlikely to change the decision materially.",
  },
  {
    slug: "meeting-decisions-actions",
    title: "Meeting to Action Register",
    intro: "Turn notes into decisions, owners, and open questions.",
    category: "Work",
    outcome: "A record people can act on without invented agreement.",
    bestFor: "Meetings or threads where ownership is easy to assume.",
    need: ["The notes or transcript", "Known attendees and project context"],
    steps: [
      "Read the source notes and restate the context.",
      "Separate decisions from suggestions.",
      "List actions, owners, and deadlines only when the source states them.",
      "Mark everything else unresolved.",
      "Check the register against the original notes.",
    ],
    produce: "Context, decisions, actions, and unresolved items.",
    failure: "Filling in an owner or a date that nobody agreed.",
    verify: "Compare decisions and owners with the source, then confirm them with the people involved.",
    example: "Use the register as the draft follow-up, not as the final record, until owners confirm it.",
    prompt:
      "From the notes below, extract context, decisions, actions, owner, due date, dependencies, and unresolved items. If an owner or deadline is not explicit, write “Not specified.” Do not infer agreement.",
  },
  {
    slug: "high-leverage-critique",
    title: "High-Leverage Critique",
    intro: "Get a short critique you can choose from, then revise once.",
    category: "Work",
    outcome: "Two improvements worth making, with evidence, and a revised version.",
    bestFor: "A draft, plan, or argument that needs judgment rather than more polish.",
    need: ["The work", "The audience and the purpose"],
    steps: [
      "State the audience and the purpose.",
      "Ask for a restatement of what the work is trying to do.",
      "Request prioritized critique with evidence from the work.",
      "Choose what to change.",
      "Revise, then ask for a focused re-review of those changes only.",
    ],
    produce: "A restatement, a short critique, and a second pass on the revision.",
    failure: "A long list of style nits that never names the highest-leverage change.",
    verify: "Keep only feedback that serves the purpose you stated.",
    example: "Limit the first critique to two changes before you rewrite.",
    prompt:
      "Review this work for [audience] and [purpose]. Restate what it is trying to achieve. Then give the two highest-leverage improvements, each with evidence from the work. Name one thing that should stay imperfect. After I revise, review only those changes.",
  },
  {
    slug: "plan-feature-safely",
    title: "Feature Before Code",
    intro: "Agree the behavior and the plan before any edit.",
    category: "Coding",
    outcome: "A reviewable plan, then small commits with tests.",
    bestFor: "A change in an existing codebase.",
    need: ["Current behavior and desired behavior", "Stack, constraints, relevant files, and conventions"],
    steps: [
      "State current behavior, desired behavior, and constraints.",
      "Ask only questions that would change the implementation.",
      "Inspect the relevant files before proposing an approach.",
      "Write the plan only. Do not modify unrelated code.",
      "Review the plan, then implement in small commits with tests.",
    ],
    produce: "A plan with affected areas, tests, and a definition of done.",
    failure: "Generating code before the existing behavior is understood.",
    verify: "Open the referenced files. Run tests, lint, and typecheck. Do not weaken those checks to make a change pass.",
    example: "Ask for the plan and stop there until someone who knows the code has read it.",
    prompt:
      "Plan [change] for [stack]. Current behavior: [current]. Desired behavior: [desired]. Inspect the context below before you propose anything. Ask only questions that would change the implementation. List affected files, approach, tests, and a definition of done. Do not write code yet, and do not modify unrelated code.",
  },
  {
    slug: "debug-without-guessing",
    title: "Debug from Evidence",
    intro: "One experiment at a time, aimed at the cause.",
    category: "Coding",
    outcome: "A root-cause fix you can re-test, plus a note on what caused it.",
    bestFor: "A bug with a reproduction, an error, or a visible mismatch.",
    need: ["Expected behavior and actual behavior", "Reproduction, error, logs, code, and recent changes"],
    steps: [
      "Reproduce the failure.",
      "Collect the error, logs, and recent changes.",
      "List hypotheses.",
      "Run one discriminating experiment.",
      "Apply the smallest fix at the cause, re-test, and record the cause.",
    ],
    produce: "A hypothesis, an experiment, a fix, and a cause note.",
    failure: "Accepting the first plausible explanation, or making tests pass by weakening them.",
    verify: "Re-run the reproduction and the relevant checks. Do not disable lint, types, or tests without an explicit reason.",
    example: "Share the smallest failing case and ask for the next experiment, not a patch.",
    prompt:
      "Help debug this from evidence. Expected: [expected]. Actual: [actual]. Reproduction, error, logs, and recent changes are below. Separate facts, hypotheses, and unknowns. Propose one discriminating experiment. Do not suggest a fix until the result is known, and do not weaken lint, types, or tests to hide the failure.",
  },
  {
    slug: "goal-breakdown",
    title: "Goal to Tomorrow",
    intro: "Connect a measurable outcome to one action you can take tomorrow.",
    category: "Planning",
    outcome: "A working plan from milestone down to tomorrow, plus a review point.",
    bestFor: "A goal with a date, ambiguity, or too many possible starts.",
    need: ["A meaningful, measurable goal", "Why it matters, advantages, and obstacles"],
    steps: [
      "State the goal so success can be observed.",
      "Name advantages, resources, and obstacles.",
      "Set the milestone, then this month and this week.",
      "Choose tomorrow’s smallest useful action.",
      "Pick when you will review the plan.",
    ],
    produce: "Milestone, month, week, tomorrow, metric, obstacle, and a review point.",
    failure: "A long activity list that never shows evidence of progress.",
    verify: "Check that the metric demonstrates the outcome, and treat the plan as a hypothesis.",
    example: "Use the Goal Breakdown tool when you want the plan in a form you can copy.",
    prompt:
      "Break [goal] down from a measurable outcome. Ask for anything missing about why it matters, the success evidence, the target, advantages, and obstacles. Then give a milestone, this month, this week, and tomorrow. Name the metric, the main obstacle, and a review point. Treat the plan as a working hypothesis.",
  },
  {
    slug: "human-in-the-loop-automation",
    title: "Human-in-the-Loop Automation",
    intro: "Automate the repeatable transformation and keep the risky decision visible.",
    category: "Automation",
    outcome: "A small pilot with validation, an approval point, and a failure path.",
    bestFor: "A process that repeats and is tempting to hand over entirely.",
    need: ["The trigger, inputs, and current steps", "What would be costly if it were wrong"],
    steps: [
      "Map the process from trigger to result.",
      "Separate deterministic steps from judgment.",
      "Automate the low-risk transformation only.",
      "Add validation, a human approval point, and a failure path.",
      "Pilot it and measure errors and time.",
    ],
    produce: "A workflow map with approval and failure handling.",
    failure: "Hiding an irreversible or high-stakes decision inside an automatic step.",
    verify: "Run edge cases. Confirm who approves consequential output before the pilot expands.",
    example: "Keep external messages, payments, and destructive changes on the human side of the line.",
    prompt:
      "Map this process: trigger, inputs, current steps, and desired output. Separate steps a machine can transform from steps a person must judge. Propose validation, a human approval point, and a failure path. Recommend a low-risk pilot and what to measure. Do not automate irreversible or high-stakes decisions.",
  },
  {
    slug: "direction-through-experiments",
    title: "Direction Through Experiments",
    intro: "Use a small experiment when the direction is unclear.",
    category: "Goals & Productivity",
    outcome: "A next experiment chosen from evidence about learning, energy, demand, and results.",
    bestFor: "A career or focus question that will not be settled by more rumination.",
    need: ["What you are learning and which skills you actually use", "A dissatisfaction you can name precisely"],
    steps: [
      "Look at whether you are learning and using distinctive skills.",
      "Name the dissatisfaction precisely.",
      "Design one small experiment.",
      "Observe learning, energy, demand, and results.",
      "Keep what transfers, then choose the next experiment.",
    ],
    produce: "One experiment and a way to read the result.",
    failure: "Waiting for a single perfect calling, or turning reflection into a score.",
    verify: "Judge the experiment by what you observed, not by a generated career rating.",
    example: "One conversation, one piece of work, or one week of a different kind of task is enough.",
    prompt:
      "Help me design one small experiment about [direction]. Ask what I am learning, which skills feel distinctive, and what dissatisfaction I can name precisely. Do not score my career. Propose one experiment and what to observe: learning, energy, demand, and results. End with what transferable learning I should keep either way.",
  },
];
