import type { PromptTemplate } from "@/types/content";

export const prompts: PromptTemplate[] = [
  {
    slug: "concept-explainer",
    title: "Concept Explainer",
    category: "Learning",
    outcome: "An explanation you can restate",
    when: "A topic feels abstract or full of jargon",
    variables: ["topic", "level", "familiar domain"],
    prompt:
      "Explain [topic] for someone at [level]. Start with a simple mental model and one analogy from [familiar domain]. Give one concrete example, one common misconception, and two questions that test whether I understand it. Define necessary jargon.",
    why: "It asks for a model, a check, and a misconception instead of a long overview.",
    verify: "Check definitions and the example against a trusted source.",
  },
  {
    slug: "socratic-tutor",
    title: "Socratic Tutor",
    category: "Learning",
    outcome: "Practice that reveals gaps",
    when: "You want to learn by answering",
    variables: ["topic", "level"],
    prompt:
      "Act as a Socratic tutor for [topic] at [level]. Ask one question at a time and wait for my answer. Prefer hints before full explanations. Correct misunderstandings clearly. Ask me to explain ideas back in my own words and finish with a new problem that tests transfer.",
    why: "The one-question rule keeps the thinking on your side of the conversation.",
    verify: "Check the correction against trusted material, then try a new example without help.",
  },
  {
    slug: "study-planner",
    title: "Study Planner",
    category: "Learning",
    outcome: "A plan built around practice",
    when: "You have a subject, a target, and limited hours",
    variables: ["subject", "level", "target", "hours per week", "duration"],
    prompt:
      "Create a study plan for [subject]. Current level: [level]. Target: [target]. Available time: [hours per week] for [duration]. Include weekly topics, active practice, retrieval, resources, and a small project or test. Do not fill the plan with passive review.",
    why: "It ties the calendar to practice and a way to tell if the plan worked.",
    verify: "Check that each week has retrieval or practice, not only reading.",
  },
  {
    slug: "flashcard-generator",
    title: "Flashcard Generator",
    category: "Learning",
    outcome: "A set of testable cards",
    when: "You have notes or a bounded source to remember",
    variables: ["source", "purpose"],
    prompt:
      "Using only the source below, create flashcards for [purpose]. One idea per card. Questions must be answerable without the card text. Keep answers concise. Mix definitions, comparisons, applications, and examples. Do not add claims the source does not support. Put the answer after the question.",
    why: "Atomic questions and a source boundary keep the deck honest.",
    verify: "Spot-check cards against the source and discard any that need the answer to make sense.",
  },
  {
    slug: "clear-email",
    title: "Clear Email",
    category: "Writing",
    outcome: "A concise email with one ask",
    when: "The request is clear and the wording is not",
    variables: ["recipient", "objective", "context", "facts", "tone", "deadline"],
    prompt:
      "Draft an email to [recipient]. Objective: [objective]. Context: [context]. Include only these facts: [facts]. Use a [tone] tone, one clear ask, and this deadline: [deadline]. Do not invent names, dates, commitments, or details. Offer two subject lines.",
    why: "It separates the facts you supplied from anything the model might add.",
    verify: "Check names, dates, promises, attachments, and tone before sending.",
  },
  {
    slug: "meeting-summarizer",
    title: "Meeting Summarizer",
    category: "Work",
    outcome: "Decisions and actions without invented owners",
    when: "Notes contain several threads",
    variables: ["notes", "context"],
    prompt:
      "Summarize the notes below. Context: [context]. Give the purpose, key decisions, action items with owner and deadline, and open questions. If an owner or deadline is missing, write “Not specified.” Do not infer agreement.",
    why: "An explicit missing-info marker is safer than a plausible owner.",
    verify: "Compare decisions with the notes, then confirm actions with the people involved.",
  },
  {
    slug: "checklist-creator",
    title: "Checklist Creator",
    category: "Work",
    outcome: "Steps someone can execute",
    when: "A process is still a description rather than a sequence",
    variables: ["process", "done"],
    prompt:
      "Turn [process] into a checklist. Group steps by phase. Begin each item with a verb. Define what “done” means: [done]. Separate mandatory and optional items, and flag dependencies. Do not add steps that the process does not require.",
    why: "Verbs, phases, and a definition of done make the list usable.",
    verify: "Walk the list once against the real process and remove steps nobody actually does.",
  },
  {
    slug: "idea-generator",
    title: "Idea Generator",
    category: "Thinking",
    outcome: "Options that differ in strategy",
    when: "The first ideas are variations of the same approach",
    variables: ["problem", "audience", "constraints"],
    prompt:
      "Generate meaningfully different approaches to [problem] for [audience] under [constraints]. Not cosmetic variants. For each option give the core strategy, assumptions, advantages, drawbacks, effort, and when you would choose it. Do not pick one for me.",
    why: "It forces a strategy difference and leaves the choice with you.",
    verify: "Drop options that only restate the same idea, and check assumptions you would actually rely on.",
  },
  {
    slug: "constructive-critic",
    title: "Constructive Critic",
    category: "Feedback",
    outcome: "A short, evidenced critique",
    when: "You need judgment without losing the point of the work",
    variables: ["work", "audience", "purpose"],
    prompt:
      "Review this work for [audience] and [purpose]. State what it is trying to achieve. Identify the two highest-leverage improvements, each with evidence from the work. Name one thing that should remain imperfect instead of being over-polished.",
    why: "A limit of two changes prevents unfocused polishing.",
    verify: "Keep feedback that matches the purpose you stated.",
  },
  {
    slug: "research-planner",
    title: "Research Planner",
    category: "Research",
    outcome: "A bounded research approach",
    when: "A question could expand without changing the decision",
    variables: ["question", "purpose", "scope", "source standard"],
    prompt:
      "Plan research on [question] for [purpose]. Scope: [scope]. Source standard: [source standard]. Define comparison criteria, exclusions, unknowns, and a stopping rule: stop when more research is unlikely to change the decision materially. Separate evidence from inference.",
    why: "The stopping rule is part of the plan, not an afterthought.",
    verify: "Inspect primary sources for the claims you will rely on, and record dates.",
  },
  {
    slug: "transparent-comparison",
    title: "Transparent Comparison",
    category: "Analysis",
    outcome: "A comparison you can challenge",
    when: "Several options look plausible",
    variables: ["options", "criteria", "constraints"],
    prompt:
      "Compare [options] against [criteria] under [constraints]. Show evidence, assumptions, trade-offs, and missing information. Suggest one small validation test. Do not hide value judgments inside a score, and do not choose for me.",
    why: "Visible assumptions are easier to argue with than a single number.",
    verify: "Check the evidence behind each criterion before you treat a trade-off as settled.",
  },
  {
    slug: "pre-mortem",
    title: "Pre-mortem",
    category: "Decisions",
    outcome: "Early signals and low-cost mitigations",
    when: "A decision feels obvious",
    variables: ["decision", "time horizon"],
    prompt:
      "Imagine [decision] failed by [time horizon]. Give plausible causes, the earliest observable signal for each, and one low-cost mitigation or test. Separate facts from speculation.",
    why: "Failure framing surfaces risks before commitment.",
    verify: "Keep only risks that have a signal you could actually notice.",
  },
  {
    slug: "function-generator",
    title: "Function Generator",
    category: "Coding",
    outcome: "A function with tests for the edges",
    when: "You can specify inputs, output, and edge cases",
    variables: ["language", "inputs", "output", "edge cases", "constraints"],
    prompt:
      "Write a [language] function. Inputs: [inputs]. Expected output: [output]. Edge cases: [edge cases]. Constraints: [constraints]. Include tests for the happy path and the edge cases. Do not broaden the function beyond this behavior.",
    why: "The tests are part of the request, so behavior is specified before code.",
    verify: "Run the tests and read the function until you can explain every branch.",
  },
  {
    slug: "code-debugger",
    title: "Code Debugger",
    category: "Coding",
    outcome: "One experiment that separates hypotheses",
    when: "A bug has more than one plausible cause",
    variables: ["expected", "actual", "reproduction", "error"],
    prompt:
      "Debug this from evidence. Expected: [expected]. Actual: [actual]. Reproduction: [reproduction]. Error and logs are below. Separate facts, hypotheses, and unknowns. Propose the cheapest experiment that distinguishes the hypotheses. Do not suggest a fix until that result is known, and do not weaken lint, types, or tests.",
    why: "It blocks a plausible patch from skipping the cause.",
    verify: "Reproduce the bug, apply the smallest cause-level fix, and re-run the checks.",
  },
  {
    slug: "code-explainer",
    title: "Code Explainer",
    category: "Coding",
    outcome: "An explanation tied to the code in front of you",
    when: "You need to understand behavior before changing it",
    variables: ["code or files", "question"],
    prompt:
      "Explain this code in service of [question]. Cover behavior, control and data flow, important functions or classes, dependencies, edge cases, and risks. Separate what the code shows from what you are inferring. End with questions I should investigate in the repository.",
    why: "It asks for flow and uncertainty, not a tour of file names.",
    verify: "Open the cited symbols and confirm the path you were given.",
  },
  {
    slug: "code-review",
    title: "Code Review",
    category: "Coding",
    outcome: "A review that does not stop at “it runs”",
    when: "Generated or new code is about to be accepted",
    variables: ["change", "requirements"],
    prompt:
      "Review this change against [requirements]. Cover correctness, requirement coverage, readability, performance, security, error handling, types, testability, maintainability, and unnecessary edits. Separate observations from assumptions. Prioritize findings and name the tests that should exist. Working output alone is not sufficient.",
    why: "The review list keeps safeguards in view.",
    verify: "Run tests, lint, and typecheck. Reject changes you cannot explain.",
  },
  {
    slug: "documentation-generator",
    title: "Documentation Generator",
    category: "Coding",
    outcome: "Docs that describe this project",
    when: "You need setup, usage, or troubleshooting written from the repo",
    variables: ["repository context", "audience"],
    prompt:
      "Document this project for [audience] using only the repository context below. Cover purpose, architecture, setup, configuration, usage, testing, deployment, contribution workflow, troubleshooting, and limitations. If something is not in the context, say it is unknown. Do not invent commands or architecture.",
    why: "An unknown is better than a confident command that does not exist.",
    verify: "Run the documented setup and test commands, and delete steps the repo does not support.",
  },
  {
    slug: "technical-planner",
    title: "Technical Planner",
    category: "Coding",
    outcome: "A plan before any code",
    when: "A product idea still needs scope and sequence",
    variables: ["vision", "constraints"],
    prompt:
      "Plan [vision] under [constraints]. Ask the questions that would change the plan. Then give outcomes, user stories, an MVP, a proposed architecture, phases, and risks. Do not write code. Stop after the plan so it can be agreed.",
    why: "It makes agreement a step, not something that happens inside a code dump.",
    verify: "Confirm the MVP and the risks with the people who will build and use it.",
  },
  {
    slug: "tech-stack-explorer",
    title: "Tech Stack Explorer",
    category: "Coding",
    outcome: "A small set of viable stacks",
    when: "You are choosing technology, especially for AI-assisted coding",
    variables: ["project", "constraints", "team", "deployment"],
    prompt:
      "Compare 3 to 5 viable, established options for [project]. Constraints: [constraints]. Team: [team]. Deployment: [deployment]. Compare complexity, ecosystem, documentation, deployment, maintainability, cost, and team familiarity. Prefer options with strong documentation when AI-assisted coding matters. Do not write code. Do not choose for me.",
    why: "A short list of established options is easier to agree than a generated favorite.",
    verify: "Check current docs, licensing, and deployment assumptions before you commit.",
  },
  {
    slug: "coding-prompt-builder",
    title: "Coding Prompt Builder",
    category: "Coding",
    outcome: "A brief another coding agent can follow",
    when: "You are about to hand a change to an AI coding tool",
    variables: ["project", "task", "current behavior", "desired behavior", "constraints"],
    prompt:
      "Write a coding brief for [project]. Task: [task]. Current behavior: [current behavior]. Desired behavior: [desired behavior]. Constraints: [constraints]. Include affected areas, acceptance criteria, tests, and non-goals. Say not to modify unrelated code and not to weaken lint, types, or tests.",
    why: "Non-goals and acceptance criteria keep the change small.",
    verify: "Read the brief against the files it names before you let an agent apply it.",
  },
  {
    slug: "goal-breakdown",
    title: "Goal Breakdown",
    category: "Planning",
    outcome: "A path from the outcome to tomorrow",
    when: "A goal is real and the next action is not",
    variables: ["goal", "metric", "target", "advantages", "obstacles"],
    prompt:
      "Break down [goal]. Success evidence: [metric]. Target: [target]. Advantages and resources: [advantages]. Obstacles: [obstacles]. Work backward from the outcome to a milestone, this month, this week, and tomorrow. Treat the plan as a working hypothesis and name a review point.",
    why: "The metric and the obstacle stay attached to the calendar.",
    verify: "Check that tomorrow’s action would actually move the metric.",
  },
  {
    slug: "task-prioritizer",
    title: "Task Prioritizer",
    category: "Planning",
    outcome: "One major task and a short support list",
    when: "The list is longer than the day",
    variables: ["objective", "tasks"],
    prompt:
      "Objective for today: [objective]. Tasks: [tasks]. Sort them with the Eisenhower distinction: important and urgent, important and not urgent, urgent and not important, neither. Urgency is not importance. Then choose one major task and no more than four support tasks. Do not decide importance for me if I have not said what matters.",
    why: "It separates the matrix from the judgment about importance.",
    verify: "Confirm the major task is the one that would make the day count.",
  },
  {
    slug: "travel-planner",
    title: "Travel Planner",
    category: "Everyday AI",
    outcome: "Options, an itinerary, and a verification list",
    when: "You are shaping a trip and live details still need checking",
    variables: ["dates", "departure", "destination", "budget", "interests", "constraints"],
    prompt:
      "Plan a trip. Dates: [dates]. From: [departure]. To: [destination]. Budget: [budget]. Interests: [interests]. Constraints: [constraints]. Give options, a draft itinerary, packing notes, and local considerations. List what I must verify myself: live prices, availability, entry rules, safety, and bookings. Do not present uncertain prices or rules as current.",
    why: "The plan is useful only if live facts stay marked as unchecked.",
    verify: "Confirm prices, availability, entry rules, safety guidance, and bookings with current official sources.",
  },
  {
    slug: "handyman-troubleshooter",
    title: "Handyman Troubleshooter",
    category: "Everyday AI",
    outcome: "One low-risk step at a time, or a stop",
    when: "A household problem might be simple, or might not",
    variables: ["problem", "tools", "skill level"],
    prompt:
      "Help me troubleshoot [problem]. Available tools: [tools]. Skill level: [skill level]. Ask clarifying questions first. If this involves electrical, gas, structural, fire, or another serious hazard, stop and tell me to use a qualified professional. Otherwise give one low-risk step at a time and say how I will know it worked.",
    why: "The safety gate comes before instructions.",
    verify: "Stop and get a qualified person for electrical, gas, structural, fire, or other serious hazards.",
  },
  {
    slug: "dictation-cleaner",
    title: "Dictation Cleaner",
    category: "Everyday AI",
    outcome: "Cleaner speech without new content",
    when: "A transcript is usable but messy",
    variables: ["transcript"],
    prompt:
      "Clean the transcript below. Fix punctuation, capitalization, filler, repetition, and paragraph breaks. Preserve my meaning and voice. Do not add facts, claims, or emphasis I did not say. If a phrase is ambiguous, leave it and mark it.",
    why: "Cleanup is a transformation, not a rewrite.",
    verify: "Read the result against the recording or transcript and remove anything you did not say.",
  },
];
