import type { UseCase } from "@/types/content";

export const useCases: UseCase[] = [
  {
    slug: "explain-a-difficult-concept",
    title: "Explain a difficult concept simply",
    description: "Turn a dense topic into a mental model, analogy, example, misconception, and test of understanding.",
    category: "Learning",
    bestFor: "A topic feels abstract or full of jargon.",
    outcome: "An explanation you can restate yourself.",
    whatYouNeed: ["The topic", "Your current level", "The part that confuses you", "An optional familiar domain for analogies"],
    workflow: [
      "State what you currently understand.",
      "Ask for a simple model.",
      "Inspect the example.",
      "Identify the misconception.",
      "Explain it back and take the critique.",
      "Solve a new example.",
    ],
    starterPrompt:
      "Explain [topic] for someone at [level]. Start with a simple mental model and one concrete analogy. Give one example, one common misconception, and two questions that test whether I actually understand it. Define necessary jargon.",
    verify: "Check technical definitions and examples against a trusted source.",
    relatedPlaybooks: ["ai-socratic-tutor"],
    relatedTools: [],
    relatedPrompts: ["concept-explainer", "socratic-tutor"],
    relatedLessons: ["accelerated-learning", "better-prompting"],
    task: "Understand",
    capability: "Explain",
    verification: "Review sources",
    tags: ["learning", "explanation"],
  },
  {
    slug: "socratic-tutor",
    title: "Work with a Socratic tutor",
    description: "Learn through questions rather than receiving finished answers.",
    category: "Learning",
    bestFor: "You have time to answer, and a finished explanation would let you skip the hard part.",
    outcome: "Stronger recall and visible knowledge gaps.",
    whatYouNeed: ["A topic and your level", "What you think you know"],
    workflow: [
      "Give the topic and your level.",
      "State what you know.",
      "Answer one question at a time.",
      "Ask for a hint before an explanation.",
      "Take the correction.",
      "Finish with a transfer question.",
    ],
    starterPrompt:
      "Act as a Socratic tutor for [topic] at [level]. Ask one question at a time and wait for my answer. Prefer hints before full explanations. Correct misunderstandings clearly. Ask me to explain ideas back in my own words and finish with a new problem that tests transfer.",
    verify: "Check corrections against trusted learning material, then try a new example alone.",
    relatedPlaybooks: ["ai-socratic-tutor"],
    relatedTools: [],
    relatedPrompts: ["socratic-tutor", "concept-explainer"],
    relatedLessons: ["accelerated-learning", "how-llms-work"],
    task: "Practice",
    capability: "Teach",
    verification: "Check reasoning",
    tags: ["learning", "questions"],
  },
  {
    slug: "learn-by-teaching",
    title: "Learn by teaching the AI",
    description: "Explain a topic from memory and use critique to locate weak spots.",
    category: "Learning",
    bestFor: "You have studied something and need to find what you cannot yet say.",
    outcome: "A short gap list and a cleaner explanation.",
    whatYouNeed: ["A topic you can attempt without notes"],
    workflow: [
      "Explain the topic without notes.",
      "Ask which links are unclear, missing, or wrong.",
      "Study only those gaps.",
      "Re-explain it simply.",
      "Test the explanation on a new example.",
    ],
    starterPrompt:
      "I will explain [topic] from memory. Do not teach yet. Mark what is unclear, missing, or incorrect. After I restudy those points, ask me to re-explain simply and give me a new example.",
    verify: "The second explanation should hold up on a new example without the notes open.",
    relatedPlaybooks: ["learn-by-teaching", "ai-socratic-tutor"],
    relatedTools: [],
    relatedPrompts: ["socratic-tutor", "concept-explainer"],
    relatedLessons: ["accelerated-learning"],
    task: "Understand",
    capability: "Critique",
    verification: "Review reasoning",
    tags: ["learning", "metacognition"],
  },
  {
    slug: "create-study-plan",
    title: "Create a study plan",
    description: "Turn a subject, a target, and the hours you actually have into a plan built on practice.",
    category: "Learning",
    bestFor: "You know the subject and the deadline, and the week is still a pile of topics.",
    outcome: "Weekly topics, active practice, retrieval, resources, and a small project or test.",
    whatYouNeed: ["Subject", "Current level", "Target", "Hours per week", "Duration or deadline"],
    workflow: [
      "State the subject, level, target, and available hours.",
      "Ask for weekly topics tied to active practice.",
      "Include retrieval, not only review.",
      "Add resources and one small project or test.",
      "Adjust the plan when a week shows a gap.",
    ],
    starterPrompt:
      "Create a study plan for [subject]. Level: [level]. Target: [target]. Time: [hours per week] until [deadline]. Include weekly topics, active practice, retrieval, resources, and a small project or test.",
    verify: "Check that the hours fit your week and that each week includes practice or retrieval.",
    relatedPlaybooks: ["learn-by-teaching"],
    relatedTools: [],
    relatedPrompts: ["study-planner", "flashcard-generator"],
    relatedLessons: ["accelerated-learning", "achieve-more"],
    task: "Plan",
    capability: "Structure",
    verification: "Human judgment",
    tags: ["study", "planning"],
  },
  {
    slug: "generate-flashcards",
    title: "Generate useful flashcards",
    description: "Create retrieval questions from a bounded source, with answers separated from the prompts.",
    category: "Learning",
    bestFor: "You have notes worth remembering and do not want a deck of vague summaries.",
    outcome: "A compact set of testable cards.",
    whatYouNeed: ["A bounded source", "The purpose of the deck"],
    workflow: [
      "Provide the source and say to use only that source.",
      "Require one idea per card.",
      "Ask for testable questions and concise answers.",
      "Mix definitions, comparison, application, and examples.",
      "Reject cards that add unsupported claims.",
    ],
    starterPrompt:
      "Using only the source below, create flashcards. One idea per card. Questions must be testable, answers concise. Mix definitions, comparisons, applications, and examples. Do not add claims the source does not support.",
    verify: "Spot-check cards against the source and remove any that smuggle in outside facts.",
    relatedPlaybooks: ["learn-by-teaching"],
    relatedTools: [],
    relatedPrompts: ["flashcard-generator", "study-planner"],
    relatedLessons: ["accelerated-learning"],
    task: "Study",
    capability: "Transform",
    verification: "Check coverage",
    tags: ["study", "memory"],
  },
  {
    slug: "quiz-yourself",
    title: "Quiz yourself before an exam",
    description: "Answer mixed-difficulty questions before you see hints, then quiz the weak areas again.",
    category: "Learning",
    bestFor: "An exam or checkpoint where recognition is not the same as recall.",
    outcome: "Evidence of what you can retrieve, and a second pass on the gaps.",
    whatYouNeed: ["A source or syllabus", "The topics in scope"],
    workflow: [
      "Supply the source or syllabus.",
      "Ask for mixed-difficulty questions.",
      "Answer without notes.",
      "Request hints only after you commit to an answer.",
      "Review the errors.",
      "Take a second quiz on the weak areas.",
    ],
    starterPrompt:
      "Quiz me on [topic] using the source below. Mix difficulties. Ask one question at a time, wait for my answer, and give a hint only after I commit. Then review my errors and give a second short quiz on the weak areas.",
    verify: "Check answers against the source, not against the model’s confidence.",
    relatedPlaybooks: ["ai-socratic-tutor", "learn-by-teaching"],
    relatedTools: [],
    relatedPrompts: ["socratic-tutor", "flashcard-generator"],
    relatedLessons: ["accelerated-learning"],
    task: "Practice",
    capability: "Evaluate",
    verification: "Check answers",
    tags: ["quiz", "practice"],
  },
  {
    slug: "study-from-documents",
    title: "Study from your own documents",
    description: "Map a document before you summarize it, then retrieve and check answers against the source.",
    category: "Learning",
    bestFor: "A report, chapter, policy, or technical document you need to learn from.",
    outcome: "A source-grounded map, questions, and a check against the original.",
    whatYouNeed: ["The document or bounded excerpts", "Your purpose and level"],
    workflow: [
      "Map the document structure before summarizing.",
      "Extract claims, terms, and evidence.",
      "Generate questions.",
      "Answer from memory.",
      "Verify answers against the source.",
    ],
    starterPrompt:
      "Use only the document below. Map its structure, key claims, terms, and evidence before you summarize. Then create retrieval questions. If the document does not support an answer, say so. Do not add outside information.",
    verify: "Open the cited passages and check claims, definitions, and anything the summary left out.",
    relatedPlaybooks: ["deep-research-workflow"],
    relatedTools: [],
    relatedPrompts: ["concept-explainer", "research-planner"],
    relatedLessons: ["accelerated-learning", "verification"],
    task: "Study",
    capability: "Synthesize",
    verification: "Source-grounded",
    tags: ["documents", "study"],
  },
  {
    slug: "language-practice",
    title: "Practice a language in context",
    description: "Hold a realistic conversation, then take short corrections without losing the thread.",
    category: "Learning",
    bestFor: "You want usable phrases in a situation, not a grammar lecture.",
    outcome: "Corrected attempts and phrases worth reviewing.",
    whatYouNeed: ["Language and level", "A scenario"],
    workflow: [
      "Set the language, level, and scenario.",
      "Converse.",
      "Ask for short corrections that preserve your meaning.",
      "Continue the conversation.",
      "Finish with phrases to review.",
    ],
    starterPrompt:
      "Practice [language] with me at [level] in this scenario: [scenario]. Stay in the conversation. After each turn, give only a short correction that preserves my meaning. End with phrases I should review.",
    verify: "Check corrections that you will reuse, especially anything formal or high-stakes.",
    relatedPlaybooks: ["ai-socratic-tutor"],
    relatedTools: [],
    relatedPrompts: ["socratic-tutor", "concept-explainer"],
    relatedLessons: ["accelerated-learning"],
    task: "Practice",
    capability: "Simulate",
    verification: "Check language",
    tags: ["language", "practice"],
  },
  {
    slug: "explore-curiosity",
    title: "Explore something you are curious about",
    description: "Map the territory, choose one branch, and leave with the next useful question.",
    category: "Learning",
    bestFor: "Interest is broad and you do not yet know which question is worth a deeper pass.",
    outcome: "A map and one question to investigate next.",
    whatYouNeed: ["The subject you are curious about", "How deep you want to go today"],
    workflow: [
      "Map the territory.",
      "Identify major concepts and questions.",
      "Choose one branch.",
      "Investigate that branch.",
      "Record the next useful question.",
    ],
    starterPrompt:
      "Help me explore [subject]. First map the major concepts and questions. Then help me choose one branch to investigate. Separate what is established from what is uncertain, and end with the next useful question.",
    verify: "Check surprising claims against a source before you treat the map as fact.",
    relatedPlaybooks: ["deep-research-workflow"],
    relatedTools: [],
    relatedPrompts: ["research-planner", "concept-explainer"],
    relatedLessons: ["accelerated-learning", "how-llms-work"],
    task: "Explore",
    capability: "Discover",
    verification: "Source-grounded",
    tags: ["curiosity", "research"],
  },
  {
    slug: "draft-improve-email",
    title: "Draft and improve an email",
    description: "Move from recipient, objective, and facts to a concise message with one ask.",
    category: "Work",
    bestFor: "The ask is clear and the wording, tone, or length is not.",
    outcome: "An email you can send after checking facts and tone.",
    whatYouNeed: ["Recipient", "Objective", "Context", "Facts", "Tone", "Requested action and deadline"],
    workflow: [
      "State the recipient, objective, and facts that may be used.",
      "Set tone, ask, and deadline.",
      "Forbid invented names, dates, and commitments.",
      "Review subject lines and the single ask.",
      "Check the draft before sending.",
    ],
    starterPrompt:
      "Draft an email to [recipient]. Objective: [objective]. Context: [context]. Include only these facts: [facts]. Use a [tone] tone and one clear ask. Do not invent names, dates, commitments, or details. Offer two subject lines.",
    verify: "Check names, dates, promises, deadlines, tone, and attachments.",
    relatedPlaybooks: ["high-leverage-critique"],
    relatedTools: [],
    relatedPrompts: ["clear-email", "constructive-critic"],
    relatedLessons: ["work-with-ai", "better-prompting"],
    task: "Create",
    capability: "Draft",
    verification: "Human review",
    tags: ["email", "writing"],
  },
  {
    slug: "summarize-meeting",
    title: "Summarize a meeting",
    description: "Separate purpose, decisions, actions, and open questions without inventing owners.",
    category: "Work",
    bestFor: "A messy transcript or notes that still need a follow-up.",
    outcome: "Purpose, decisions, actions with owner and deadline, and open questions.",
    whatYouNeed: ["Notes or a transcript", "Context the notes assume"],
    workflow: [
      "Provide the notes and the context.",
      "Ask for purpose, decisions, actions, and open questions.",
      "Require “Not specified” when an owner or deadline is missing.",
      "Read the summary against the notes.",
    ],
    starterPrompt:
      "Summarize these notes. Give purpose and context, key decisions, action items with owner and deadline, and open questions. If an owner or deadline is missing, write “Not specified.” Do not invent them.",
    verify: "Check decisions against the notes. Confirm owners with the group.",
    relatedPlaybooks: ["meeting-decisions-actions"],
    relatedTools: [],
    relatedPrompts: ["meeting-summarizer", "checklist-creator"],
    relatedLessons: ["work-with-ai"],
    task: "Organize",
    capability: "Summarize",
    verification: "Human review",
    tags: ["meetings", "notes"],
  },
  {
    slug: "extract-decisions-actions",
    title: "Extract decisions and action items",
    description: "Turn discussion into decisions, owners, actions, due dates, dependencies, and unknowns.",
    category: "Work",
    bestFor: "A conversation where agreement and ownership are easy to over-read.",
    outcome: "An action register you can verify against the original notes.",
    whatYouNeed: ["The discussion notes", "Any context needed to read them"],
    workflow: [
      "Extract decisions separately from suggestions.",
      "List owners, due dates, and dependencies only when stated.",
      "Mark unknowns.",
      "Verify the register against the original notes.",
    ],
    starterPrompt:
      "From these notes, extract decisions, owners, actions, due dates, dependencies, and unknowns. If something was not stated, mark it unknown. Do not infer consensus.",
    verify: "Compare every decision and owner with the original notes.",
    relatedPlaybooks: ["meeting-decisions-actions"],
    relatedTools: [],
    relatedPrompts: ["meeting-summarizer", "checklist-creator"],
    relatedLessons: ["work-with-ai", "verification"],
    task: "Organize",
    capability: "Extract",
    verification: "Human review",
    tags: ["decisions", "actions"],
  },
  {
    slug: "create-checklist",
    title: "Create a checklist",
    description: "Turn a process into steps someone can execute, grouped by phase.",
    category: "Work",
    bestFor: "A process people describe differently and still need to follow.",
    outcome: "A checklist with verbs, a definition of done, and visible dependencies.",
    whatYouNeed: ["The process", "What done means", "Any known dependencies"],
    workflow: [
      "Describe the process and what done means.",
      "Group steps by phase.",
      "Begin items with verbs.",
      "Separate mandatory and optional steps.",
      "Flag dependencies.",
    ],
    starterPrompt:
      "Turn [process] into a checklist. Group by phase, start each item with a verb, define done, separate mandatory and optional steps, and flag dependencies.",
    verify: "Walk the list against the real process and remove steps that do not belong.",
    relatedPlaybooks: ["meeting-decisions-actions"],
    relatedTools: [],
    relatedPrompts: ["checklist-creator", "clear-email"],
    relatedLessons: ["work-with-ai"],
    task: "Organize",
    capability: "Structure",
    verification: "Human review",
    tags: ["checklist", "process"],
  },
  {
    slug: "prepare-conversation",
    title: "Prepare for an important conversation",
    description: "Clarify the outcome, the facts, the likely objections, and the commitments you should not make yet.",
    category: "Work",
    bestFor: "A conversation with stakes, disagreement, or an easy way to over-promise.",
    outcome: "A calmer plan: opening, questions, boundaries, and what to leave undecided.",
    whatYouNeed: ["The desired outcome", "Facts you will rely on", "The commitment you must not make early"],
    workflow: [
      "Clarify the desired outcome.",
      "Separate facts from assumptions.",
      "List likely objections and questions.",
      "Set boundaries and an opening.",
      "Name commitments to avoid making prematurely.",
    ],
    starterPrompt:
      "Help me prepare for a conversation about [topic]. Desired outcome: [outcome]. Facts I can rely on: [facts]. List assumptions, likely objections, questions to ask, an opening, and commitments I should not make yet.",
    verify: "Check the facts you plan to state, and decide the boundary yourself.",
    relatedPlaybooks: ["high-leverage-critique"],
    relatedTools: [],
    relatedPrompts: ["clear-email", "constructive-critic"],
    relatedLessons: ["work-with-ai"],
    task: "Prepare",
    capability: "Simulate",
    verification: "Human judgment",
    tags: ["communication", "meetings"],
  },
  {
    slug: "critique-work",
    title: "Critique a piece of work",
    description: "Ask for two high-leverage improvements with evidence, and one thing to leave imperfect.",
    category: "Work",
    bestFor: "A draft that needs judgment, not another full rewrite.",
    outcome: "Two improvements you can choose to make.",
    whatYouNeed: ["The work", "The audience", "The purpose"],
    workflow: [
      "State the audience and purpose.",
      "Ask what the work is trying to achieve.",
      "Request two improvements with evidence from the work.",
      "Ask what should stay imperfect.",
      "Decide which feedback matches your intent.",
    ],
    starterPrompt:
      "Review this work for [audience] and [purpose]. State what it is trying to achieve, then identify the two highest-leverage improvements with concrete evidence. Name one thing that should remain imperfect instead of being over-polished.",
    verify: "Keep feedback that serves the purpose. Discard the rest.",
    relatedPlaybooks: ["high-leverage-critique"],
    relatedTools: [],
    relatedPrompts: ["constructive-critic", "idea-generator"],
    relatedLessons: ["work-with-ai", "better-prompting"],
    task: "Improve",
    capability: "Critique",
    verification: "Human judgment",
    tags: ["feedback", "editing"],
  },
  {
    slug: "brainstorm-alternatives",
    title: "Brainstorm alternative approaches",
    description: "Generate approaches that differ in strategy, then compare them against constraints.",
    category: "Work",
    bestFor: "The obvious options are variations of one idea.",
    outcome: "A small set of comparable approaches.",
    whatYouNeed: ["The problem", "Constraints", "What would count as meaningfully different"],
    workflow: [
      "State the problem and constraints.",
      "Ask for approaches with different strategies, not cosmetic variants.",
      "For each, capture strategy, assumptions, advantages, drawbacks, effort, and when to choose it.",
      "Compare them yourself.",
    ],
    starterPrompt:
      "Generate meaningfully different approaches to [problem] under [constraints]. For each, give the core strategy, assumptions, advantages, drawbacks, effort, and the conditions for choosing it. Do not pick for me.",
    verify: "Reject options that are the same strategy in new words, and check assumptions you would act on.",
    relatedPlaybooks: ["high-leverage-critique"],
    relatedTools: [],
    relatedPrompts: ["idea-generator", "transparent-comparison"],
    relatedLessons: ["work-with-ai"],
    task: "Explore",
    capability: "Ideate",
    verification: "Human judgment",
    tags: ["ideas", "options"],
  },
  {
    slug: "persuasive-case",
    title: "Prepare a persuasive case",
    description: "Build a case with evidence, counterarguments, and a clear request, in short and longer forms.",
    category: "Work",
    bestFor: "You need someone to understand a position and a specific ask.",
    outcome: "A short version, a detailed version, and the action you are requesting.",
    whatYouNeed: ["Your position", "The audience", "The evidence you can actually use"],
    workflow: [
      "Clarify the position and the audience.",
      "Identify the evidence.",
      "Anticipate counterarguments and prepare rebuttals.",
      "Draft a short version and a detailed version.",
      "End with a clear requested action.",
    ],
    starterPrompt:
      "Help me make the case for [position] to [audience]. Use only this evidence: [evidence]. Anticipate counterarguments, prepare brief rebuttals, and give a short version and a detailed version. End with one requested action. Do not invent evidence.",
    verify: "Check every factual claim and make sure the ask is one you are willing to make.",
    relatedPlaybooks: ["high-leverage-critique"],
    relatedTools: [],
    relatedPrompts: ["constructive-critic", "clear-email"],
    relatedLessons: ["work-with-ai"],
    task: "Prepare",
    capability: "Draft",
    verification: "Human review",
    tags: ["persuasion", "writing"],
  },
  {
    slug: "notes-to-structure",
    title: "Turn notes into structure",
    description: "Find themes, facts, gaps, and contradictions before you choose a final format.",
    category: "Work",
    bestFor: "Raw notes that are not yet a brief, plan, or outline.",
    outcome: "Themes, gaps, a proposed structure, and questions that still need answers.",
    whatYouNeed: ["The notes", "The format you might need later"],
    workflow: [
      "Read for themes and important facts.",
      "Surface gaps and contradictions.",
      "Propose a structure.",
      "List questions that must be resolved before the structure is trustworthy.",
    ],
    starterPrompt:
      "From these notes, list themes, important facts, gaps, and contradictions. Then propose a structure and the questions I still need to resolve. Do not smooth over disagreements in the notes.",
    verify: "Check that important facts still match the notes after they are reorganized.",
    relatedPlaybooks: ["meeting-decisions-actions"],
    relatedTools: [],
    relatedPrompts: ["meeting-summarizer", "checklist-creator"],
    relatedLessons: ["work-with-ai"],
    task: "Organize",
    capability: "Structure",
    verification: "Human review",
    tags: ["notes", "synthesis"],
  },
  {
    slug: "deep-research",
    title: "Run a deep research pass",
    description: "Define the question, source standard, and stopping rule before you collect evidence.",
    category: "Research",
    bestFor: "A question where more links will not automatically make a better decision.",
    outcome: "A traceable synthesis with evidence, inference, and unknowns kept apart.",
    whatYouNeed: ["Question and purpose", "Scope, date range, geography, exclusions, and source standard"],
    workflow: [
      "Define the question, purpose, scope, and exclusions.",
      "Set the source standard and stopping rule.",
      "Search broadly, then inspect primary sources.",
      "Separate evidence, inference, and unknowns.",
      "Stop when more research is unlikely to change the decision materially.",
    ],
    starterPrompt:
      "Help me research [question] for [purpose]. Define scope, dates, geography, source standard, exclusions, and a stopping rule. For each important claim, separate evidence, inference, and unknowns. Name the sources I must inspect.",
    verify: "Open primary sources for claims you will rely on. Check dates.",
    relatedPlaybooks: ["deep-research-workflow"],
    relatedTools: [],
    relatedPrompts: ["research-planner", "transparent-comparison"],
    relatedLessons: ["verification", "how-llms-work"],
    task: "Investigate",
    capability: "Research",
    verification: "Source-grounded",
    tags: ["research", "sources"],
  },
  {
    slug: "compare-alternatives",
    title: "Compare alternatives with criteria",
    description: "Show evidence, assumptions, trade-offs, and a small test without hiding judgment in a score.",
    category: "Research",
    bestFor: "Several options look reasonable and the criteria are still implicit.",
    outcome: "A comparison you can challenge, plus one validation test.",
    whatYouNeed: ["The options", "Criteria and constraints", "Evidence you already have"],
    workflow: [
      "List options, criteria, and constraints.",
      "Show evidence and assumptions for each.",
      "Make trade-offs visible.",
      "Name missing information.",
      "Add one small validation test. Do not choose for the user.",
    ],
    starterPrompt:
      "Compare [options] against [criteria] under [constraints]. Show evidence, assumptions, trade-offs, missing information, and a small validation test. Do not hide value judgments inside arbitrary scores, and do not choose for me.",
    verify: "Check the evidence behind the criteria before you treat a trade-off as fact.",
    relatedPlaybooks: ["deep-research-workflow"],
    relatedTools: [],
    relatedPrompts: ["transparent-comparison", "pre-mortem"],
    relatedLessons: ["verification", "work-with-ai"],
    task: "Decide",
    capability: "Compare",
    verification: "Source-grounded",
    tags: ["comparison", "decisions"],
  },
  {
    slug: "document-map",
    title: "Map a document before summarizing",
    description: "Find structure, claims, terms, evidence, assumptions, and omissions before a summary.",
    category: "Research",
    bestFor: "A long or unfamiliar document where a summary would hide what was skipped.",
    outcome: "A map and the questions the document leaves open.",
    whatYouNeed: ["The document", "Why you are reading it"],
    workflow: [
      "Map structure, claims, and terms.",
      "Note evidence, assumptions, and omissions.",
      "List questions.",
      "Summarize only after the map exists.",
    ],
    starterPrompt:
      "Using only the document below, map its structure, claims, terms, evidence, assumptions, and omissions. List questions for [purpose]. Quote short support for important claims. Summarize only after the map.",
    verify: "Open the passages cited and notice what the summary leaves out.",
    relatedPlaybooks: ["deep-research-workflow"],
    relatedTools: [],
    relatedPrompts: ["research-planner", "concept-explainer"],
    relatedLessons: ["verification", "accelerated-learning"],
    task: "Explore",
    capability: "Map",
    verification: "Source-grounded",
    tags: ["documents", "mapping"],
  },
  {
    slug: "key-takeaways",
    title: "Extract key takeaways",
    description: "Pull the ideas that matter for a defined audience and purpose, not the sentences that repeat most.",
    category: "Research",
    bestFor: "A source is long and “important” depends on what you will do with it.",
    outcome: "A short set of takeaways tied to a purpose.",
    whatYouNeed: ["The source", "The audience", "The purpose"],
    workflow: [
      "State the audience and purpose.",
      "Ask for the ideas that matter for that purpose.",
      "Require a reason each takeaway matters.",
      "Ignore importance based only on how often a sentence appears.",
    ],
    starterPrompt:
      "From the source below, extract the takeaways that matter for [audience] and [purpose]. For each, say why it matters to that purpose. Do not rank ideas by how often they are repeated. Say what the source does not settle.",
    verify: "Check takeaways against the source and drop any that serve a different purpose than yours.",
    relatedPlaybooks: ["deep-research-workflow"],
    relatedTools: [],
    relatedPrompts: ["concept-explainer", "research-planner"],
    relatedLessons: ["accelerated-learning", "verification"],
    task: "Synthesize",
    capability: "Extract",
    verification: "Source-grounded",
    tags: ["summary", "purpose"],
  },
  {
    slug: "research-purchase",
    title: "Research a purchase",
    description: "Compare options against requirements, then verify live price and availability yourself.",
    category: "Research",
    bestFor: "A purchase where marketing claims and stale prices are easy to trust.",
    outcome: "A comparison of current evidence, with uncertain claims flagged.",
    whatYouNeed: ["Requirements", "Must-haves and preferences", "Budget and constraints"],
    workflow: [
      "Define requirements, must-haves, preferences, budget, and constraints.",
      "Compare the evidence you have.",
      "Flag uncertain claims.",
      "Verify live price, availability, and policies before buying.",
    ],
    starterPrompt:
      "Help me research a purchase. Requirements: [requirements]. Must-haves: [must-haves]. Preferences: [preferences]. Budget and constraints: [constraints]. Compare evidence, flag uncertain claims, and list what I must verify live: price, availability, and relevant policies. Do not present prices as current.",
    verify: "Confirm live price, availability, return rules, and any safety or compatibility claims before you buy.",
    relatedPlaybooks: ["deep-research-workflow"],
    relatedTools: [],
    relatedPrompts: ["transparent-comparison", "research-planner"],
    relatedLessons: ["verification", "everyday-automation"],
    task: "Decide",
    capability: "Compare",
    verification: "Source-grounded",
    tags: ["purchase", "comparison"],
  },
  {
    slug: "feature-plan",
    title: "Plan a feature before writing code",
    description: "Restate the behavior, inspect the code, and agree a plan before implementation.",
    category: "Coding",
    bestFor: "A change that crosses existing code and should not start as a generated patch.",
    outcome: "An implementation plan with tests and a definition of done.",
    whatYouNeed: ["Project and stack", "The request", "Current and desired behavior", "Constraints, relevant files, and conventions"],
    workflow: [
      "Inspect the architecture and restate the behavior.",
      "Ask only questions that would change the implementation.",
      "Identify affected files and explain the approach before changes.",
      "Break the work into small changes and define tests.",
      "Implement only after the plan is reviewed. Do not modify unrelated code.",
    ],
    starterPrompt:
      "Plan [request] for [stack]. Current behavior: [current]. Desired behavior: [desired]. Constraints: [constraints]. Ask only questions that would change the implementation. List affected files, the approach, tests, and a definition of done. Do not write code yet, and do not modify unrelated code.",
    verify: "Open the files. Run tests, lint, and typecheck. Keep those checks intact.",
    relatedPlaybooks: ["plan-feature-safely"],
    relatedTools: ["coding-task-brief"],
    relatedPrompts: ["technical-planner", "coding-prompt-builder"],
    relatedLessons: ["better-coder"],
    task: "Plan",
    capability: "Structure",
    verification: "Run tests",
    tags: ["coding", "planning"],
  },
  {
    slug: "debug-evidence",
    title: "Debug from evidence",
    description: "Reproduce the failure, test one hypothesis, and fix the cause rather than the symptom.",
    category: "Coding",
    bestFor: "A bug with expected behavior, actual behavior, and something you can reproduce.",
    outcome: "A tested hypothesis, a smallest fix, and a re-test.",
    whatYouNeed: ["Expected and actual behavior", "Reproduction, error, logs, code, and recent changes"],
    workflow: [
      "Reproduce the failure.",
      "List hypotheses from the evidence.",
      "Run one discriminating experiment.",
      "Apply the smallest root-cause fix.",
      "Re-test. Do not weaken lint, types, or tests to hide the failure.",
    ],
    starterPrompt:
      "Debug this from evidence. Expected: [expected]. Actual: [actual]. Reproduction, error, logs, code, and recent changes are below. Separate facts and hypotheses. Propose one discriminating experiment. Do not suggest a fix until the result is known, and do not weaken lint, types, or tests.",
    verify: "Reproduce, fix the cause, and re-run the checks.",
    relatedPlaybooks: ["debug-without-guessing"],
    relatedTools: ["coding-task-brief"],
    relatedPrompts: ["code-debugger", "code-review"],
    relatedLessons: ["better-coder", "verification"],
    task: "Diagnose",
    capability: "Debug",
    verification: "Run tests",
    tags: ["coding", "debugging"],
  },
  {
    slug: "code-explainer",
    title: "Explain existing code",
    description: "Explain behavior, flow, dependencies, edge cases, and what is still an inference.",
    category: "Coding",
    bestFor: "You need a working understanding before you change anything.",
    outcome: "An explanation you can check in the code, plus questions to investigate.",
    whatYouNeed: ["The code or file references", "The question you need answered"],
    workflow: [
      "Ask for behavior, control flow, and data flow.",
      "Identify key functions or classes and dependencies.",
      "Note edge cases and risks.",
      "Separate observations from inferences.",
      "List investigation questions.",
    ],
    starterPrompt:
      "Explain this code for [question]. Cover behavior, control and data flow, key functions or classes, dependencies, edge cases, and risks. Separate observations from inferences, and end with questions I should check in the repository.",
    verify: "Open the symbols mentioned and confirm the path.",
    relatedPlaybooks: ["plan-feature-safely"],
    relatedTools: [],
    relatedPrompts: ["code-explainer", "code-review"],
    relatedLessons: ["better-coder"],
    task: "Understand",
    capability: "Explain",
    verification: "Run tests",
    tags: ["coding", "reading"],
  },
  {
    slug: "review-ai-code",
    title: "Review AI-generated code",
    description: "Check correctness, requirements, security, and safeguards. Working output is not enough.",
    category: "Coding",
    bestFor: "Generated code is about to be accepted.",
    outcome: "A prioritized review and the tests that should exist.",
    whatYouNeed: ["The change", "The requirements", "How the project checks quality"],
    workflow: [
      "Review correctness and requirement coverage.",
      "Check security, error handling, types, and performance.",
      "Look for maintainability problems, missing tests, and unnecessary changes.",
      "Name assumptions.",
      "Run the project’s checks before accepting.",
    ],
    starterPrompt:
      "Review this change against [requirements]. Cover correctness, requirement coverage, security, error handling, types, performance, maintainability, tests, unnecessary changes, and assumptions. Prioritize findings. Working output alone is not sufficient.",
    verify: "Run tests, lint, and typecheck. Do not merge code you cannot explain.",
    relatedPlaybooks: ["debug-without-guessing", "plan-feature-safely"],
    relatedTools: [],
    relatedPrompts: ["code-review", "code-debugger"],
    relatedLessons: ["better-coder", "verification"],
    task: "Audit",
    capability: "Review",
    verification: "Run tests",
    tags: ["coding", "review"],
  },
  {
    slug: "refactor-safely",
    title: "Refactor safely",
    description: "Preserve behavior, establish checks, and change one seam at a time.",
    category: "Coding",
    bestFor: "The structure should change and the behavior should not.",
    outcome: "A low-risk sequence of reversible changes.",
    whatYouNeed: ["The behavior that must stay the same", "Tests or checks that demonstrate it", "The area you want to change"],
    workflow: [
      "State the behavior to preserve.",
      "Establish tests or checks.",
      "Identify seams.",
      "Make one reversible change.",
      "Run the checks, then continue.",
    ],
    starterPrompt:
      "Help me refactor [area] without changing behavior. Behavior to preserve: [behavior]. Propose seams and one reversible change at a time. Name the checks to run after each change. Do not bundle unrelated edits.",
    verify: "Run the checks after each change. Stop if behavior moved.",
    relatedPlaybooks: ["plan-feature-safely"],
    relatedTools: [],
    relatedPrompts: ["code-review", "coding-prompt-builder"],
    relatedLessons: ["better-coder"],
    task: "Improve",
    capability: "Review",
    verification: "Run tests",
    tags: ["coding", "refactoring"],
  },
  {
    slug: "docs-generator",
    title: "Document the project you have",
    description: "Write setup, architecture, and troubleshooting from the repository, not from a generic template.",
    category: "Coding",
    bestFor: "Docs are missing, and invented commands would be worse than a gap.",
    outcome: "Documentation of purpose, setup, usage, testing, deployment, and limits.",
    whatYouNeed: ["Repository context", "The audience", "Commands and files you know are real"],
    workflow: [
      "Provide the actual project context.",
      "Cover purpose, architecture, setup, configuration, and usage.",
      "Include testing, deployment, contribution, troubleshooting, and limitations.",
      "Mark anything not supported by the context as unknown.",
    ],
    starterPrompt:
      "Document this project for [audience] using only the context below. Cover purpose, architecture, setup, configuration, usage, testing, deployment, contribution, troubleshooting, and limitations. If the context does not support a command or decision, say it is unknown.",
    verify: "Run the documented commands. Delete steps the project does not support.",
    relatedPlaybooks: ["plan-feature-safely"],
    relatedTools: [],
    relatedPrompts: ["documentation-generator", "code-explainer"],
    relatedLessons: ["better-coder"],
    task: "Create",
    capability: "Draft",
    verification: "Run tests",
    tags: ["coding", "docs"],
  },
  {
    slug: "choose-tech-stack",
    title: "Choose a tech stack",
    description: "Compare a few established options on the constraints that will matter after the prototype.",
    category: "Coding",
    bestFor: "A stack decision is still open and code would freeze it too early.",
    outcome: "Three to five viable options and the trade-offs that need a human decision.",
    whatYouNeed: ["The project", "Constraints", "Team familiarity", "Deployment needs"],
    workflow: [
      "Ask the questions that would change the choice.",
      "Prefer established technology with strong documentation when AI-assisted coding matters.",
      "Compare 3 to 5 viable options.",
      "Cover complexity, ecosystem, deployment, maintainability, cost, and team familiarity.",
      "Do not write code before the choice is agreed.",
    ],
    starterPrompt:
      "Help me choose a stack for [project]. Constraints: [constraints]. Team: [team]. Deployment: [deployment]. Ask high-leverage questions, then compare 3 to 5 established options on complexity, ecosystem, documentation, deployment, maintainability, cost, and familiarity. Do not write code, and do not choose for me.",
    verify: "Check current documentation, licensing, and deployment claims before you agree.",
    relatedPlaybooks: ["plan-feature-safely"],
    relatedTools: [],
    relatedPrompts: ["tech-stack-explorer", "technical-planner"],
    relatedLessons: ["better-coder", "choosing-tools"],
    task: "Decide",
    capability: "Compare",
    verification: "Human judgment",
    tags: ["coding", "stack"],
  },
  {
    slug: "design-ai-workflow",
    title: "Design an AI-assisted workflow",
    description: "Map the process, automate the low-risk transformation, and keep approval visible.",
    category: "Automation",
    bestFor: "A repeated process that might be partly automatable.",
    outcome: "A workflow with validation, approval, a failure path, and a pilot.",
    whatYouNeed: ["Trigger and input", "Manual steps", "Desired output", "Frequency, risk, and who approves"],
    workflow: [
      "Map trigger, input, manual steps, and desired output.",
      "Mark which transformation is suitable for AI.",
      "Define validation, risk, approval, and failure handling.",
      "Pilot low-risk examples.",
      "Measure errors and time saved.",
    ],
    starterPrompt:
      "Design an AI-assisted workflow. Trigger: [trigger]. Input: [input]. Current steps: [steps]. Desired output: [output]. Frequency: [frequency]. Show the AI transformation, validation, human approval, and failure path. Recommend a low-risk pilot and what to measure.",
    verify: "Test edge cases and confirm who approves consequential output.",
    relatedPlaybooks: ["human-in-the-loop-automation"],
    relatedTools: ["automation-mapper"],
    relatedPrompts: ["checklist-creator", "technical-planner"],
    relatedLessons: ["everyday-automation", "practical-workflow"],
    task: "Design",
    capability: "Workflow",
    verification: "Human approval",
    tags: ["automation", "workflow"],
  },
  {
    slug: "human-approval",
    title: "Decide where human approval remains",
    description: "Keep people on irreversible, high-stakes, and ambiguous decisions. Automate the rest more readily.",
    category: "Automation",
    bestFor: "A workflow is forming and it is unclear which steps may proceed alone.",
    outcome: "A clear approval line.",
    whatYouNeed: ["The steps", "What happens if a step is wrong", "Which actions are reversible"],
    workflow: [
      "List the steps and their consequences.",
      "Keep human approval for irreversible actions, financial commitments, high-stakes decisions, sensitive external messages, ambiguous consequential output, and destructive operations.",
      "Allow more automation for lower-risk formatting, extraction, classification, drafts, and reversible routing.",
      "Write the rule down.",
    ],
    starterPrompt:
      "Here is a workflow: [steps]. For each step, say whether a human should approve it. Keep approval for irreversible actions, financial commitments, high-stakes decisions, sensitive external messages, ambiguous consequential output, and destructive operations. Lower-risk formatting, extraction, classification, drafts, and reversible routing can be automated more readily. Do not hide the risky steps.",
    verify: "Review the line with the person accountable for the consequence.",
    relatedPlaybooks: ["human-in-the-loop-automation"],
    relatedTools: ["automation-mapper"],
    relatedPrompts: ["pre-mortem", "checklist-creator"],
    relatedLessons: ["everyday-automation", "verification"],
    task: "Decide",
    capability: "Evaluate",
    verification: "Human approval",
    tags: ["automation", "risk"],
  },
  {
    slug: "pressure-test-idea",
    title: "Pressure-test an idea",
    description: "Ask for assumptions, counterarguments, edge cases, and cheap tests instead of agreement.",
    category: "Thinking",
    bestFor: "An idea is starting to sound finished before it has been stressed.",
    outcome: "A clearer idea, or a reason to stop.",
    whatYouNeed: ["The idea", "What would count as a cheap test"],
    workflow: [
      "State the idea.",
      "Ask for assumptions, counterarguments, edge cases, and missing evidence.",
      "Ask for failure modes and cheap experiments.",
      "Separate facts from speculation.",
    ],
    starterPrompt:
      "Pressure-test this idea: [idea]. Give assumptions, counterarguments, edge cases, missing evidence, failure modes, and one cheap experiment. Separate facts from speculation. Do not agree with me by default.",
    verify: "Keep only challenges you can connect to evidence or a test.",
    relatedPlaybooks: ["high-leverage-critique"],
    relatedTools: [],
    relatedPrompts: ["pre-mortem", "constructive-critic"],
    relatedLessons: ["practical-workflow", "verification"],
    task: "Evaluate",
    capability: "Critique",
    verification: "Human judgment",
    tags: ["thinking", "ideas"],
  },
  {
    slug: "generate-options",
    title: "Generate and compare options",
    description: "Produce genuinely different proposals, critique them, and compare them against criteria you choose.",
    category: "Thinking",
    bestFor: "You need range before a decision, not a single recommended answer.",
    outcome: "A comparison a person can decide from.",
    whatYouNeed: ["The problem", "Criteria", "Constraints and exclusions"],
    workflow: [
      "Generate multiple proposals that differ in substance.",
      "Critique them.",
      "Compare them against explicit criteria.",
      "Leave the decision to a person.",
    ],
    starterPrompt:
      "Generate several genuinely different proposals for [problem] under [constraints]. Critique each one, then compare them against [criteria]. Do not choose for me.",
    verify: "Check that the options are actually different, and that the criteria are yours.",
    relatedPlaybooks: ["high-leverage-critique"],
    relatedTools: [],
    relatedPrompts: ["idea-generator", "transparent-comparison"],
    relatedLessons: ["practical-workflow", "work-with-ai"],
    task: "Explore",
    capability: "Ideate",
    verification: "Human judgment",
    tags: ["options", "decisions"],
  },
  {
    slug: "decision-premortem",
    title: "Run a decision pre-mortem",
    description: "Imagine the decision failed, then name causes, early signals, and low-cost mitigations.",
    category: "Thinking",
    bestFor: "A choice feels settled and the failure modes are still vague.",
    outcome: "A decision with named risks and signals.",
    whatYouNeed: ["The decision", "The time horizon", "Constraints"],
    workflow: [
      "Imagine the decision has failed after a defined horizon.",
      "List plausible causes.",
      "Name the earliest signal for each.",
      "Add one low-cost mitigation or test.",
      "Separate facts from speculation.",
    ],
    starterPrompt:
      "Imagine [decision] failed by [time horizon]. Give plausible causes, the earliest signal for each, and one low-cost mitigation or test. Separate facts from speculation.",
    verify: "Keep risks that have an observable signal.",
    relatedPlaybooks: ["high-leverage-critique"],
    relatedTools: [],
    relatedPrompts: ["pre-mortem", "transparent-comparison"],
    relatedLessons: ["practical-workflow", "verification"],
    task: "Decide",
    capability: "Simulate",
    verification: "Human judgment",
    tags: ["decisions", "risk"],
  },
  {
    slug: "breakdown-goal",
    title: "Break down a large goal",
    description: "Move from a meaningful outcome to a milestone, a month, a week, and tomorrow.",
    category: "Planning",
    bestFor: "The outcome matters and the plan is still a slogan.",
    outcome: "A working hypothesis: milestone, month, week, tomorrow, metric, and obstacle.",
    whatYouNeed: ["The goal", "Why it matters", "Success evidence", "Target, advantages, and obstacles"],
    workflow: [
      "Use the sequence Big Goal, milestone, month, week, tomorrow.",
      "Include why, success evidence, target, advantages, and obstacles.",
      "Treat the plan as a working hypothesis.",
      "Name a review point.",
    ],
    starterPrompt:
      "Break down [goal]. Why it matters: [why]. Success evidence: [metric]. Target: [target]. Advantages: [advantages]. Obstacles: [obstacles]. Give a milestone, this month, this week, and tomorrow. Treat the plan as a working hypothesis.",
    verify: "Check that the metric shows the outcome, not just activity.",
    relatedPlaybooks: ["goal-breakdown"],
    relatedTools: ["goal-breakdown"],
    relatedPrompts: ["goal-breakdown", "task-prioritizer"],
    relatedLessons: ["achieve-more", "go-faster"],
    task: "Plan",
    capability: "Structure",
    verification: "Human judgment",
    tags: ["goals", "planning"],
  },
  {
    slug: "plan-backwards",
    title: "Plan backwards from a date",
    description: "Start from the definition of done and walk back through dependencies, checkpoints, and buffer.",
    category: "Planning",
    bestFor: "A date is real and the work between here and there is not.",
    outcome: "A schedule with dependencies, checkpoints, and buffer.",
    whatYouNeed: ["The date", "The definition of done", "Known dependencies"],
    workflow: [
      "Write the definition of done.",
      "Work backward through dependencies.",
      "Place milestones and checkpoints.",
      "Add buffer.",
      "Name the first checkpoint you will actually review.",
    ],
    starterPrompt:
      "Plan backward from [date]. Definition of done: [done]. Known dependencies: [dependencies]. Give milestones, checkpoints, and buffer. Mark assumptions. Do not hide a dependency by shrinking the work.",
    verify: "Check that the buffer and dependencies match how the work actually happens.",
    relatedPlaybooks: ["goal-breakdown"],
    relatedTools: ["goal-breakdown"],
    relatedPrompts: ["goal-breakdown", "task-prioritizer"],
    relatedLessons: ["achieve-more"],
    task: "Plan",
    capability: "Structure",
    verification: "Human judgment",
    tags: ["planning", "deadlines"],
  },
  {
    slug: "choose-daily-priorities",
    title: "Choose daily priorities",
    description: "Pick one major task and no more than four supporting tasks.",
    category: "Goals & Productivity",
    bestFor: "The list is longer than the day.",
    outcome: "A realistic day: one meaningful task, then support.",
    whatYouNeed: ["Today’s objective", "The candidate tasks"],
    workflow: [
      "Choose one major task: the difficult, meaningful task that makes the day count.",
      "Add no more than four minor or support tasks.",
      "Do the major task first when that is feasible.",
    ],
    starterPrompt:
      "Help me choose today’s work. Objective: [objective]. Tasks: [tasks]. Recommend one major task and at most four support tasks. The major task is the one that makes the day count. Ask me if importance is unclear instead of assuming it.",
    verify: "Confirm the major task is yours to judge, then protect time for it.",
    relatedPlaybooks: ["goal-breakdown"],
    relatedTools: ["daily-five"],
    relatedPrompts: ["task-prioritizer", "goal-breakdown"],
    relatedLessons: ["go-faster", "achieve-more"],
    task: "Prioritize",
    capability: "Evaluate",
    verification: "Human judgment",
    tags: ["productivity", "focus"],
  },
  {
    slug: "eisenhower-matrix",
    title: "Sort work with the Eisenhower Matrix",
    description: "Separate importance from urgency, then decide what to do, schedule, delegate, or drop.",
    category: "Goals & Productivity",
    bestFor: "Urgent tasks are crowding out important ones.",
    outcome: "Four lists and a judgment you made yourself.",
    whatYouNeed: ["The tasks", "What “important” means for you right now"],
    workflow: [
      "Important and urgent: do now.",
      "Important and not urgent: schedule.",
      "Not important and urgent: delegate.",
      "Neither: remove or leave for later.",
      "Let the tool organize. You judge importance.",
    ],
    starterPrompt:
      "Sort these tasks into Do now, Schedule, Delegate, and Remove or later. Important and urgent is Do now. Important and not urgent is Schedule. Not important and urgent is Delegate. Neither is Remove or later. Urgency is not importance. Ask me when importance is ambiguous.",
    verify: "Review the important-but-not-urgent list. That is the one urgency tends to erase.",
    relatedPlaybooks: ["goal-breakdown"],
    relatedTools: ["eisenhower-matrix"],
    relatedPrompts: ["task-prioritizer", "goal-breakdown"],
    relatedLessons: ["go-faster", "go-further"],
    task: "Prioritize",
    capability: "Evaluate",
    verification: "Human judgment",
    tags: ["priorities", "matrix"],
  },
  {
    slug: "match-work-energy",
    title: "Match work to energy",
    description: "Place demanding, moderate, and routine work against the energy pattern you actually observe.",
    category: "Goals & Productivity",
    bestFor: "Hard work keeps landing in the part of the day when you are least able to do it.",
    outcome: "A personal energy map and one scheduling experiment.",
    whatYouNeed: ["When energy is high, medium, and low", "The kinds of work you do"],
    workflow: [
      "Put demanding work in peak energy.",
      "Put collaborative or moderate work in medium energy.",
      "Put routine and admin work in low energy.",
      "Treat the map as an observation, not a permanent identity.",
      "Try one scheduling experiment.",
    ],
    starterPrompt:
      "Help me match work to energy. Peak: [peak]. Medium: [medium]. Low: [low]. Suggest where demanding, collaborative, and routine work fits. Treat this as an observed map, not an identity, and propose one scheduling experiment.",
    verify: "Notice what the experiment changes. Revise the map if the pattern does not hold.",
    relatedPlaybooks: ["goal-breakdown"],
    relatedTools: ["energy-matching"],
    relatedPrompts: ["task-prioritizer", "goal-breakdown"],
    relatedLessons: ["go-faster", "go-further"],
    task: "Plan",
    capability: "Personalize",
    verification: "Human judgment",
    tags: ["energy", "planning"],
  },
  {
    slug: "identify-blockers",
    title: "Identify productivity blockers",
    description: "Name up to three recurring blockers and test one small change this week.",
    category: "Goals & Productivity",
    bestFor: "The same friction keeps returning.",
    outcome: "One change you can test, and a question for what you observe.",
    whatYouNeed: ["Recent examples of the friction", "Willingness to change one thing"],
    workflow: [
      "Choose up to three blockers from the real pattern, not a long confession.",
      "Pick one small change this week.",
      "Decide what you will observe before and after.",
    ],
    starterPrompt:
      "Help me examine up to three productivity blockers. Recent examples: [examples]. Candidates include social media, email, notifications, task switching, fear of failure, perfectionism, energy, requests from others, lack of purpose, inability to say no, sleep, communication barriers, unrealistic planning, decision fatigue, environment, skill gaps, and burnout. Propose one small change to test this week and one observation question. Do not assume a personality flaw.",
    verify: "Judge the change by what happens in the next real example.",
    relatedPlaybooks: ["direction-through-experiments"],
    relatedTools: ["productivity-blockers"],
    relatedPrompts: ["task-prioritizer", "pre-mortem"],
    relatedLessons: ["go-further", "go-faster"],
    task: "Improve",
    capability: "Diagnose",
    verification: "Human judgment",
    tags: ["productivity", "habits"],
  },
  {
    slug: "weekly-review",
    title: "Run a weekly review",
    description: "Look at evidence from the week and choose one focus, not another wish list.",
    category: "Goals & Productivity",
    bestFor: "The week happened and the lesson is still mixed in with the activity.",
    outcome: "A grounded note: achievement, learning, blocker, progress, change, and next focus.",
    whatYouNeed: ["What happened", "Evidence of progress", "The blocker that mattered"],
    workflow: [
      "Record the main achievement and key learning.",
      "Name the blocker and the progress evidence.",
      "Note what changed.",
      "Choose one focus for next week.",
    ],
    starterPrompt:
      "Review this week. Main achievement: [achievement]. Learning: [learning]. Blocker: [blocker]. Progress evidence: [progress]. What changed: [change]. Separate evidence from interpretation and propose one focus for next week.",
    verify: "Check that next week’s focus follows from the evidence, not from a new ambition.",
    relatedPlaybooks: ["goal-breakdown", "direction-through-experiments"],
    relatedTools: ["weekly-review"],
    relatedPrompts: ["goal-breakdown", "task-prioritizer"],
    relatedLessons: ["go-further", "achieve-more"],
    task: "Reflect",
    capability: "Synthesize",
    verification: "Human judgment",
    tags: ["review", "reflection"],
  },
  {
    slug: "review-direction",
    title: "Check whether you are moving in the right direction",
    description: "Ask better questions about learning, skills, and fear, then design a small experiment.",
    category: "Goals & Productivity",
    bestFor: "Direction feels unclear and a score would pretend otherwise.",
    outcome: "Better questions and one experiment, not a deterministic answer.",
    whatYouNeed: ["What you are learning", "Skills you use", "Goals that are yours", "What you are avoiding"],
    workflow: [
      "Ask: Am I learning? Am I using distinctive skills? Am I progressing toward goals that are mine?",
      "Ask what comes unusually easily, and what you are avoiding from fear.",
      "Ask which habits belong to an earlier stage.",
      "Choose a small experiment that would create useful information.",
    ],
    starterPrompt:
      "Help me review direction without scoring a career. Ask about learning in my current work, distinctive skills, goals that are mine, what comes easily, what I am avoiding from fear, and habits from an earlier stage. Then propose one small experiment and what information it would give me.",
    verify: "Judge the experiment by what you learn. Do not treat a generated rating as an answer.",
    relatedPlaybooks: ["direction-through-experiments"],
    relatedTools: ["current-situation-review"],
    relatedPrompts: ["pre-mortem", "goal-breakdown"],
    relatedLessons: ["right-direction", "go-further"],
    task: "Reflect",
    capability: "Question",
    verification: "Human judgment",
    tags: ["direction", "reflection"],
  },
  {
    slug: "travel-planning",
    title: "Plan travel without trusting stale details",
    description: "Shape options, an itinerary, and a packing list, then verify anything that can change.",
    category: "Everyday AI",
    bestFor: "You want structure for a trip and know prices and rules go stale.",
    outcome: "A draft plan plus the live facts you still have to confirm.",
    whatYouNeed: ["Dates, departure, and destination", "Budget, interests, and constraints"],
    workflow: [
      "Structure options, itinerary, packing, and local considerations.",
      "Mark prices, availability, and rules as unverified.",
      "Independently confirm live prices, availability, entry rules, safety, and bookings.",
    ],
    starterPrompt:
      "Plan a trip. Dates: [dates]. From: [departure]. To: [destination]. Budget: [budget]. Interests: [interests]. Constraints: [constraints]. Give options, a draft itinerary, packing notes, and local considerations. List what I must verify: live prices, availability, entry rules, safety, and bookings.",
    verify: "Confirm live prices, availability, entry rules, safety guidance, and bookings yourself.",
    relatedPlaybooks: ["deep-research-workflow"],
    relatedTools: [],
    relatedPrompts: ["travel-planner", "research-planner"],
    relatedLessons: ["everyday-automation", "verification"],
    task: "Plan",
    capability: "Structure",
    verification: "Human review",
    tags: ["travel", "planning"],
  },
  {
    slug: "ingredients-to-meal",
    title: "Turn ingredients into a meal",
    description: "Suggest meals from what you have, plus diet, time, equipment, and preferences.",
    category: "Everyday AI",
    bestFor: "You want a practical meal idea and still need to judge food safety yourself.",
    outcome: "Meal ideas that fit the constraints you stated.",
    whatYouNeed: ["Ingredients on hand", "Diet, time, equipment, and preferences"],
    workflow: [
      "List ingredients and constraints.",
      "Ask for meals that fit them.",
      "Verify food safety and any health-specific requirement yourself.",
    ],
    starterPrompt:
      "Suggest meals from these ingredients: [ingredients]. Diet: [diet]. Time: [time]. Equipment: [equipment]. Preferences: [preferences]. Note assumptions. Do not claim a meal is safe for a medical diet unless I verify that requirement.",
    verify: "Check food safety, allergens, and any health-specific requirement with an appropriate source.",
    relatedPlaybooks: ["human-in-the-loop-automation"],
    relatedTools: [],
    relatedPrompts: ["checklist-creator", "research-planner"],
    relatedLessons: ["everyday-automation", "verification"],
    task: "Create",
    capability: "Ideate",
    verification: "Human review",
    tags: ["cooking", "everyday"],
  },
  {
    slug: "household-troubleshooting",
    title: "Troubleshoot a household problem",
    description: "Get diagnostic questions and one low-risk step at a time, and stop when the hazard is serious.",
    category: "Everyday AI",
    bestFor: "Something at home might have a simple cause, or might need a professional.",
    outcome: "Either a careful next step or a clear reason to stop.",
    whatYouNeed: ["The problem", "Your tools and skill level"],
    workflow: [
      "Ask diagnostic questions first.",
      "If the issue is electrical, gas, structural, fire, or another serious hazard, stop and use a qualified professional.",
      "Otherwise proceed one low-risk step at a time.",
    ],
    starterPrompt:
      "Help me troubleshoot [problem]. Tools: [tools]. Skill level: [skill]. Ask diagnostic questions first. If this is electrical, gas, structural, fire, or another serious hazard, stop and tell me to call a qualified professional. Otherwise give one low-risk step at a time.",
    verify: "Escalate electrical, gas, structural, fire, and other serious hazards to a qualified professional.",
    relatedPlaybooks: ["human-in-the-loop-automation"],
    relatedTools: [],
    relatedPrompts: ["handyman-troubleshooter", "checklist-creator"],
    relatedLessons: ["everyday-automation", "verification"],
    task: "Diagnose",
    capability: "Diagnose",
    verification: "Human judgment",
    tags: ["household", "safety"],
  },
  {
    slug: "dictation-cleanup",
    title: "Clean up dictation",
    description: "Fix punctuation, filler, and paragraphs while preserving meaning and voice.",
    category: "Everyday AI",
    bestFor: "A transcript is usable and must not gain new facts in the cleanup.",
    outcome: "A cleaner version of what you said.",
    whatYouNeed: ["The transcript or dictated text"],
    workflow: [
      "Ask for punctuation, capitalization, filler, repetition, and paragraph fixes.",
      "Require the meaning and voice to stay.",
      "Forbid new facts.",
      "Compare the result with what you said.",
    ],
    starterPrompt:
      "Clean this dictation. Fix punctuation, capitalization, filler, repetition, and paragraphs. Preserve my meaning and voice. Add no new facts. Mark anything ambiguous instead of resolving it.",
    verify: "Read the result against the original and remove anything you did not say.",
    relatedPlaybooks: ["high-leverage-critique"],
    relatedTools: [],
    relatedPrompts: ["dictation-cleaner", "clear-email"],
    relatedLessons: ["everyday-automation", "better-prompting"],
    task: "Improve",
    capability: "Transform",
    verification: "Human review",
    tags: ["writing", "dictation"],
  },
  {
    slug: "live-interpreter",
    title: "Use AI as a live interpreter",
    description: "Translate between two languages without joining the conversation, and escalate when accuracy is critical.",
    category: "Everyday AI",
    bestFor: "A practical conversation where a rough translation helps and the stakes are limited.",
    outcome: "Translations that stay in the translator role.",
    whatYouNeed: ["Both languages", "The kind of conversation", "Whether accuracy is ordinary or critical"],
    workflow: [
      "Define both languages.",
      "Ask for translation only, without added opinions or joining the conversation.",
      "Use a qualified interpreter where legal, medical, or other high-stakes accuracy is critical.",
    ],
    starterPrompt:
      "Translate between [language A] and [language B]. Do not join the conversation, advise, or add content. Translate only what I paste. If I say the setting is legal, medical, or otherwise high-stakes, tell me to use a qualified interpreter instead of continuing.",
    verify: "For legal, medical, or other high-stakes accuracy, use a qualified interpreter.",
    relatedPlaybooks: ["human-in-the-loop-automation"],
    relatedTools: [],
    relatedPrompts: ["clear-email", "dictation-cleaner"],
    relatedLessons: ["everyday-automation", "verification"],
    task: "Create",
    capability: "Transform",
    verification: "Human judgment",
    tags: ["translation", "everyday"],
  },
];
